### PR TITLE
Basic styling included with the package. Bumping version.

### PR DESCRIPTION
**Pull request by droka**
I suggest to include the very basic Jquery styling together with this package, so it looks well.
(other styling like bootstrap should be sold separately, but some basic is good to have here)

### CODE REVIEW

**Comment by droka** [comment]
Apart from this, Im working on the issue, of being able to i18n the title row.
That is not possible at the moment, and would be important for my project.
When I can get that to working, I will send PR with that,
and after that I suggest to bump the version, and reupload to atmosphere, so that others can benefit from the fixes. As the atmosphere version is quite old. Does not have the table styling classes feature either.

**Comment by raphaelarias** [comment]
It is possible to i18n the title of the row. I'm using it. Just use the 'label' key when creating the table.

**Comment by raphaelarias** [comment]
I don't think it should include the CSS. Everyone will have a different need, and is better to have control.

**Comment by ephemer** [comment]
Hi, sorry, I haven't used this package in years myself. We just use plain datatables and provide the data to it manually. I'm going to close this and archive the repo. Looks like there are a bunch of forks that are more actively maintained. Thanks for using reactive-datatables!

**Pull request closed without merging**
