### PR TITLE
Allow setting table class

### PR DESCRIPTION
**Pull request by ndastur**
Allow styling of the table with other table classes. E.g. BS3 table-striped

### CODE REVIEW

**Comment by robhunt3r** [comment]
Please, this, now.

**Comment by robhunt3r** [comment]
Please, this, now. :(

**Comment by ephemer** [comment]
Sorry, for some reason I don't get email notifications about this repo. Very frustrating. Just merged your PR.

**Comment by droka** [comment]
This was merged into the git code, but was not released to Atmosphere. So I'm unable to use this feature,  unless I clone this package into my meteor project locally.
Which is OK for me at this point. Just letting you know.

**Comment by cricku** [comment]
@droka - I have the same problem. @ephemer can you release the last version on Atmosphere? I need to use these package in production?

**Pull request merged**
